### ISSUE TITLE
Request/bug [afr.com.au] - some pages not loaded properly. 

### ISSUE THREAD

**Issue by chanpreetsal** [bpc-clone/bypass-paywalls-chrome-clean#174]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Not all the articles on afr.com.au work. Only displays the first couple of paragraphs. 

Link of paywalled article: 

For example, the below two articles dont load
https://www.afr.com/technology/did-russia-just-sabotage-our-samsung-watch-ultra-20240801-p5jycr 
https://www.afr.com/property/residential/here-are-the-10-most-expensive-homes-in-australia-20240730-p5jxlj

whereas these load fine
https://www.afr.com/world/north-america/australians-to-get-fast-entry-to-us-in-global-program-20240806-p5jzto
https://www.afr.com/politics/federal/unis-to-be-capped-at-40pc-overseas-students-20240805-p5jzm0

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
Tried this in chrome , edge on 2 computers. 

Browser (main version):  Edge. 

BPC-extension version (number): 3.6.7.0

**Comment by dhdco** [comment]
@chanpreetsal 3.6.7.0 is an older version of the addon. The current version is 3.7.8.0 and I see no problem with any articles on the afr.

**Comment by chanpreetsal** [comment]
Yes, thanks updating to the latest version fixed the issue.
