### ISSUE TITLE
Financial Times is broken [ft.com]

### ISSUE THREAD

**Issue by lishuhang** [bpc-clone/bypass-paywalls-chrome-clean#45]
Describe issue/request: 

![image](https://github.com/bpc-clone/bypass-paywalls-chrome-clean/assets/49574/3cf0a939-9742-470a-9863-d2e90c8a0539)

Link of paywalled article: 

https://www.ft.com/content/77248f04-ea59-496f-93bc-36d413e8a2c9?

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

tested all those methods above and reinstalled the extension.

Browser (main version): Edge / Windows 11 / 124.0.2478.80

BPC-extension version (number): 3.6.7.1

(I have a tip says v3.6.7.4 is ready but i can't find download link for it)

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by RH383** [comment]
Still broken, but archive link works.

**Comment by lishuhang** [comment]
Thanks! I've been downloading from the release page before, so I might be a bit later than the latest updates.
